### ISSUE TITLE
Build error on dev version

### ISSUE THREAD

**Issue by hunse** [pyopencl/pyopencl#81]
I'm able to install the newest release (2015.1) using the instructions [here](http://wiki.tiker.net/PyOpenCL/Installation/Linux/Ubuntu). (By the way, these instructions need to be updated, since `configure.py` no longer seems to take boost arguments. [EDIT: Sorry, it's just in `master` that boost arguments no longer work. They're fine in `v2015.1`.] Also, it's a bit confusing having documentation both at that site and at http://documen.tician.de/pyopencl/.)

But when I try to build what's currently in master, I get a bunch of errors. I've posted the first one below.
```
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -fwrapv -Wall -O3 -DNDEBUG -fPIC -DPYGPU_PACKAGE=pyopencl -DPYGPU_PYOPENCL=1 -DPYOPENCL_USE_DEVICE_FISSION=1 -I/opt/AMDAPP/include -Isrc/c_wrapper/ -I/usr/include/python2.7 -c src/c_wrapper/wrap_cl.cpp -o build/temp.linux-x86_64-2.7/src/c_wrapper/wrap_cl.o -std=c++0x
In file included from src/c_wrapper/clhelper.h:1:0,
                 from src/c_wrapper/wrap_cl.cpp:2:
src/c_wrapper/error.h: In instantiation of ‘void call_guarded(cl_int (*)(ArgTypes ...), const char*, ArgTypes2&& ...) [with ArgTypes2 = {device* const, int, ArgBuffer<_cl_platform_id*, (ArgType)1>, std::nullptr_t}; ArgTypes = {_cl_device_id*, unsigned int, long unsigned int, void*, long unsigned int*}; cl_int = int]’:
src/c_wrapper/device.h:39:17:   required from here
src/c_wrapper/error.h:218:51: error: no matching function for call to ‘CLArgPack<device* const, int, ArgBuffer<_cl_platform_id*, (ArgType)1>, std::nullptr_t>::clcall(cl_int (*&)(_cl_device_id*, unsigned int, long unsigned int, void*, long unsigned int*), const char*&)’
     cl_int status_code = argpack.clcall(func, name);
                                                   ^
```

**Comment by inducer** [comment]
What's your gcc version?

**Comment by hunse** [comment]
gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4

**Comment by inducer** [comment]
Do you have a newer gcc available to test by any chance?

**Comment by hunse** [comment]
Tried 4.9.2. Same error.

**Comment by larsmans** [comment]
I get the exact same error, and then 700 more lines of stderr, Using GCC 4.8.4 and 4.9.0-20140405.

**Comment by larsmans** [comment]
`git bisect` suggests 299975d34c371b4ecb070bbaeba4262b3ddef8d6 is the culprit, but I did get other compile errors along the way that I marked as "good" because they looked unrelated.

**Comment by larsmans** [comment]
Did another bisect, this time a bit more carefully. 299975d34c371b4ecb070bbaeba4262b3ddef8d6 is actually the last good commit. 3f3621d, which introduced the whole C++11 metamagic templating thing, broke the build.

**Comment by silgon** [comment]
I just compiled 299975d34c371b4ecb070bbaeba4262b3ddef8d6, but I cannot use `LocalMemory`. It tells me:
```
AttributeError: 'module' object has no attribute 'LocalMemory'
```
Is there any workaround? Because the master revision gives me the same error that is posted in  the beginning.

**Comment by bmilde** [comment]
Same errors with current master and gcc (Ubuntu 4.8.5-1ubuntu1~14.04) 4.8.5

**Comment by inducer** [comment]
Should be fixed along with #83 in e12f38a38729dab3e6ac36749d25fc0bce4dbfd7.

**Comment by UniqueFool** [comment]
note that the package distributed via pip does not yet contain the patch: https://pypi.python.org/pypi/pyopencl
